create or replace PROCEDURE DHWAMAZONKP.LOAD_FACTSALESKP
IS
BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE DWHAMAZONKP.FACTSALESKP';

    INSERT INTO DWHAMAZONKP.FACTSALESKP
        (PRODUCTKEY, CUSTOMERKEY, SALEDATEKEY, QTYSOLD, SALESAMOUNT, DELIVERYDATEKEY, LOCATIONKEY)
    SELECT s.PID AS PRODUCTKEY, s.CID AS CUSTOMERKEY,
    dt1.DATEKEY AS SALEDATEKEY, s.qtysold as QTYSOLD, s.saleskpamount as SALESAMOUNT,
    dt2.datekey as DELIVERYDATEKEY, dl.LOCATIONKEY
    FROM AMAZONSTAGEKP.saleskp s
    LEFT JOIN DWHAMAZONKP.dimtimekp dt1
        ON s.saledate = dt1.fulldate
    LEFT JOIN DWHAMAZONKP.dimtimekp dt2
        ON s.deliverydate = dt2.fulldate
    LEFT JOIN AMAZONSTAGEKP.customermasterkp cm
        ON s.cid = cm.cid
    LEFT JOIN DWHAMAZONKP.DIMLOCATIONKP dl
        ON dl.city = cm.city;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN RAISE;
END LOAD_FACTSALESKP;
